##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_flutter_services
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_flutter_services
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/RobertMollentze
- https://github.com/sponsors/robmllze
description: Includes service classes for Flutter to help with state management.
version: 0.1.5
topics:
  - services
  - state-management
  - dependency-injection
  
## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter
    
  df_di: ^0.15.2
  df_pod: ^0.18.10
  df_safer_dart: ^0.17.3
  df_log: ^0.3.20
  df_type: ^0.14.2

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.5
  df_safer_dart_lints: ^0.3.3
